[package]
name = "serialbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.3.0"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib"]